### ISSUE TITLE
Beacon v2 default schemas & procedures

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2-default-schemas#2]
While I understand that the schemas here are mostly placeholders for external reference schemas, we should directly start with adopting such from SchemaBlocks, where they exist.

Example `Age`:
```
    Age:
      description: |
        Definition of age of individual at baseline as age and/or age group.
      type: object
      properties:
        age:
          description: |
            Value indicating the age of the individual at the time of collection in the ISO8601 duration format P[n]Y[n]M[n]DT[n]H[n]M[n]S
          type: string
          example: 'P32Y6M1D'
        ageGroup:
          description: |
            Categorical value from NCIT Age Group ontology classifying the individuals in age groups.
          type: string
          example: 'NCIT:C17600'
```

... is a re-definition, similar to the [_Phenopackets_ derived `Age`](https://github.com/phenopackets/phenopacket-schema/blob/master/docs/age.rst), which has a JSON-Schema representation in [{S}[B]](https://schemablocks.org/schemas/sb-phenopackets/Age.html):

```
{
  "$id": "https://schemablocks.org/schemas/sb-phenopackets/Age/v0.0.1",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": "",
  "description": "Age",
  "examples": [
    {
      "age": "P14Y"
    }
  ],
  "meta": {
    "contributors": [
      {
        "description": "Michael Baudis",
        "id": "orcid:0000-0002-9903-4248"
      },
      {
        "description": "Jules Jacobsen",
        "id": "orcid:0000-0002-3265-15918"
      },
      {
        "description": "Peter Robinson",
        "id": "orcid:0000-0002-0736-91998"
      }
    ],
    "provenance": [
      {
        "description": "Phenopackets",
        "id": "https://github.com/phenopackets/phenopacket-schema/blob/master/docs/age.rst"
      }
    ],
    "sb_status": "implemented",
    "used_by": [
      {
        "description": "Phenopackets",
        "id": "https://github.com/phenopackets/phenopacket-schema/blob/master/docs/age.rst"
      }
    ]
  },
  "properties": {
    "age": {
      "description": "Age as ISO8601 period",
      "examples": [
        "P12Y"
      ],
      "type": "string"
    }
  },
  "required": [
    "age"
  ],
  "title": "Age",
  "type": "object"
}
```

However, the Beacon v2 schema example for age also contains an `AgeGroup` attribute, which IMO is helpful (we have frequently samples from "childhood tumors" etc.); and AFAIK there actually was a class based age option in Phenopackets, previously.

So, my suggestion would be to:

1. Have the schemas as separate documents, using the *{S}[B]* format (e.g. [`BeaconGenomicVariant`](https://github.com/ga4gh-schemablocks/sb-beacon-api/blob/master/schemas/BeaconGenomicVariant.yaml)) -  and improving this, where necessary
2. Use the *{S}[B]* schemas, where existing, and request changes from upstream (e.g. GA4GH workstreams), where necessary
3. Add needed, Beacon specific schemas (e.g. all the different query types - some for v1.n [have already been prototyped in  *{S}[B]*](https://schemablocks.org/tags/Beacon.html) and [on the Beacon website](https://beacon-project.io/tags/code.html)
