### ISSUE TITLE
[suggestion] rename GenomicFeature.class to GenomicFeature.featureClass

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/specification-v2-default-schemas#34]
GenomicFeature has two properties:  
```
  featureId  
  class
```
Just to be more coherent:  
```
  featureId    
  featureClass
```

**Comment by mbaudis** [comment]
```
id
label
```
... as in all `OntologyTerm` parameters? A "Feature" having a "featureId" isn't very elegant :-)

**Comment by redmitry** [comment]
>  "Feature" having a "featureId" isn't very elegant :-)
Well, this is what we currently have... ( #4)
```
'featureClass' -> '[feature]id'
'featureId' -> 'label'
```
if fatureId == label do we need GenomicFeature at all?

'genomicRegions' is an array[OntologyTerm]
while
'genomicFeatures' is array[GenomicFeature]

**Comment by mbaudis** [comment]
I should look at the code first :-/ 

Which is different from what I'd thought & I understand the problem, I guess:

```
GenomicFeature:
      properties:
        class:
          allOf:
            - description: |
                Class of feature affected by the variant. Value from ENSGLOSS 
                Biotype (ENSGLOSSARY:0000025) ontology, e.g. protein coding gene, 
                non-coding RNA, long non-coding RNA.
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example:
                id: 'ENSGLOSSARY:0000026'
                label: 'protein coding'
        featureId:
          description: |
            ID/accession/name of genomic region affected by the variant, 
            matching class in `class`.
          type: string
          example:
            - 'TP53'
            - 'GeneID:43740578'
```

In that light it really makes sense to have `featureId` and `featureClass` (or whatever; `class` is a bit special IMO). But then have both just being `OntologyTerm` instances:

```
GenomicFeature:
      properties:
        featureClass:
          allOf:
            - description: |
                Class of feature affected by the variant. Value from ENSGLOSS 
                Biotype (ENSGLOSSARY:0000025) ontology, e.g. protein coding gene, 
                non-coding RNA, long non-coding RNA.
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
            - example:
                id: 'ENSGLOSSARY:0000026'
                label: 'protein coding'
        featureId:
          allOf:
            - description: |
               D/accession/name of genomic region affected by the variant, 
               matching class in `featureClass `.
            - $ref: 'common.yaml#/components/schemas/OntologyTerm'
              example:
                - id: 'GeneID:7157'
                  label: 'TP53'
```
... just for the symmetry.
