### ISSUE TITLE
Use of "named Ids"

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/specification-v2-default-schemas#4]
The current use of `namedId` parameters seems odd; usually (?) objects would be addressed by their `object.id` value (e.g. `biosample.id` for accessing a document in `biosamples`.

```
Biosample:
  id:
    description: The system-local unique identifier of this biosample, referenced to as "biosampleId".
  individualId:
    description: The system-local unique identifier of the individual this biosample was derived from.
Individual:
  id:
    description: The system-local unique identifier of this individual, referenced to as "individualId".
...
```

In the current schemas it would be `biosample.biosampleId` etc. ([`individualId`](https://github.com/ga4gh-beacon/specification-v2-default-schemas/blob/master/default_schemas.yaml#L258) ...).

@sdelatorrep Please elaborate.
